notifications:
  webhooks:
    urls:
      - https://chat.hyperledger.org/hooks/nJZwwsK9GKsetJhaK/jbmxG8sYC45oGGpiDfQNf9QamQyDEvM5BgTcCA5d9JZeCnX5
    on_success: always # default: always
    on_failure: always # default: always
    on_start: always   # default: never
    on_cancel: always # default: always
    on_error: always # default: always
