version: 2
jobs:
  build:
    working_directory: /ametsuchi
    docker:
      - image: lebdron/iroha-ametsuchi-dev
        environment:
          AMETSUCHI_HOME: /ametsuchi
      - image: postgres:9.5
        environment:
          POSTGRES_PASSWORD: $PGPASSWORD
      - image: redis:3.2.8
    steps:
      - checkout
      - run:
          name: cmake
          command: cmake -H. -Bbuild
      - run:
          name: make
          command: cmake --build build
      - run:
          name: run tests
          command: cmake --build build --target test
